### ISSUE TITLE
1.13+ CommandAPI

### ISSUE THREAD

**Issue by FazziCLAY** [owoPeef/MurderMystery#2]
Может быть стоит исполтзовать CommandAPI для взаимодействия с командами, вместо BukkitAPI? BukkitAPI обязан поддерживать старые версии, а которых нету синтаксиса команд которые появились в 1.13+ (brigadier)
Так вот CommandAPI как раз и добавляет возможности использовать штуки появившиеся в 1.13

https://commandapi.jorel.dev/

**Comment by owoPeef** [comment]
Может быть, будет добавлено
